### ISSUE TITLE
When can we expect code / demo to be released to public?

### ISSUE THREAD

**Issue by maheswarantp** [IntelLabs/multimodal_cognitive_ai#1]

**Comment by baeseongsu** [comment]
Same here for the NeuroPrompts research work. Is there an update on the public release of the code/demo?

**Comment by PhillipHoward** [comment]
Thank you for your patience. The code for NeuroPrompts is now available here: https://github.com/IntelLabs/multimodal_cognitive_ai/tree/main/Demos/NeuroPrompts
