### ISSUE TITLE
Support for Gemma 2?

### ISSUE THREAD

**Issue by shan23chen** [IntelLabs/multimodal_cognitive_ai#34]
Hi,

I am wondering whether this support training for second gen Gemma based llava.

When we trained with the new Gemma with this repo, we ran into an error of:

TypeError: '<' not supported between instances of 'NoneType' and 'int'

And debugging lead us to a weir huggingface past key cache bug. Wondering whether you guys have any idea how to solve it.

Thanks!

**Comment by mattolson93** [comment]
Hi, I am not sure about this bug. We currently have no plans to test Gemma2 for the llava_gemma project.
